
# Site settings
title: Liu Zeng
name: Liu Zeng
subtitle:  Student
email: zl1024@sjtu.edu.cn
description: >
   Student
baseurl: ""
url: "https://zengliuivy.github.io/"
github_username:  zengliuivy
disqus_baseurl: "https://zengliuivy.github.io/"
disqus_shortname: https-zengliuivy-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Liu Zeng"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: zengliuivy
    url: https://github.com/zengliuivy
    desc: Fork me on GitHub
    share: false

  - name: CSDN
    icon: CSDN
    username: zengliu_ivy
    url: https://blog.csdn.net/qjtx_08051005?spm=1000.2115.3001.5343
    desc: Connect with me on CSDN
    share: true
